[package]
name = "rococo-westend-system-emulated-network"
description = "Rococo<>Westend emulated bridged network"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
emulated-integration-tests-common.workspace = true
rococo-emulated-chain.workspace = true
westend-emulated-chain.workspace = true
westend-emulated-chain.default-features = true
asset-hub-rococo-emulated-chain.workspace = true
asset-hub-westend-emulated-chain.workspace = true
bridge-hub-rococo-emulated-chain.workspace = true
bridge-hub-westend-emulated-chain.workspace = true
penpal-emulated-chain.workspace = true
bifrost-polkadot-emulated-chain = { path = "../../../integration-tests/chains/bifrost-polkadot" }
bifrost-kusama-emulated-chain = { path = "../../../integration-tests/chains/bifrost-kusama" }
