// This file is part of Bifrost.

// Copyright (C) Liebi Technologies PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for bb_bnc
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-03-26, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `bifrost-jenkins`, CPU: `Intel(R) Xeon(R) CPU E5-26xx v4`
//! WASM-EXECUTION: Compiled, CHAIN: Some("bifrost-polkadot-local"), DB CACHE: 1024

// Executed Command:
// target/release/bifrost
// benchmark
// pallet
// --chain=bifrost-polkadot-local
// --steps=50
// --repeat=20
// --pallet=bb_bnc
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/bifrost-polkadot/src/weights/bb_bnc.rs
// --template=./weight-template/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions for bb_bnc.
pub struct BifrostWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> bb_bnc::WeightInfo for BifrostWeight<T> {
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:0)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757`
		// Minimum execution time: 19_932 nanoseconds.
		Weight::from_parts(20_979_000, 3757)
			.saturating_add(T::DbWeight::get().reads(2))
	}
	// Storage: `BbBNC::BbConfigs` (r:1 w:1)
	// Proof: `BbBNC::BbConfigs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1654`
		// Minimum execution time: 30_595 nanoseconds.
		Weight::from_parts(31_157_000, 1654)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: `BbBNC::Position` (r:1 w:1)
	// Proof: `BbBNC::Position` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPositions` (r:1 w:1)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::BbConfigs` (r:1 w:0)
	// Proof: `BbBNC::BbConfigs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Locked` (r:1 w:1)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Supply` (r:1 w:1)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserLocked` (r:1 w:1)
	// Proof: `BbBNC::UserLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:0)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:1)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:0)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:2 w:1)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:0 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:0 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_lock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1446`
		//  Estimated: `7386`
		// Minimum execution time: 244_789 nanoseconds.
		Weight::from_parts(247_576_000, 7386)
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(18))
	}
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::BbConfigs` (r:1 w:0)
	// Proof: `BbBNC::BbConfigs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:1)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Supply` (r:1 w:1)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserLocked` (r:1 w:1)
	// Proof: `BbBNC::UserLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:0)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:1)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:1)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:1 w:1)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn increase_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2380`
		//  Estimated: `5845`
		// Minimum execution time: 310_904 nanoseconds.
		Weight::from_parts(335_144_000, 5845)
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::BbConfigs` (r:1 w:0)
	// Proof: `BbBNC::BbConfigs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:1)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Supply` (r:1 w:1)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Accounts` (r:1 w:0)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:0)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:1)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:1)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:2 w:2)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn increase_unlock_time() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1617`
		//  Estimated: `7557`
		// Minimum execution time: 252_456 nanoseconds.
		Weight::from_parts(256_906_000, 7557)
			.saturating_add(T::DbWeight::get().reads(20))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	// Storage: `BbBNC::UserPositions` (r:1 w:1)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:1)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Supply` (r:1 w:1)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserLocked` (r:1 w:1)
	// Proof: `BbBNC::UserLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:53)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:52 w:0)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:0)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:0 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:0 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:0 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2227`
		//  Estimated: `131917`
		// Minimum execution time: 742_278 nanoseconds.
		Weight::from_parts(760_593_000, 131917)
			.saturating_add(T::DbWeight::get().reads(69))
			.saturating_add(T::DbWeight::get().writes(68))
	}
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Epoch` (r:1 w:0)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:0)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:52 w:0)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:0)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:0)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:0)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:0 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn get_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `923`
		//  Estimated: `130613`
		// Minimum execution time: 357_986 nanoseconds.
		Weight::from_parts(364_970_000, 130613)
			.saturating_add(T::DbWeight::get().reads(60))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:0)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:0)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:2 w:2)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `Balances::TotalIssuance` (r:1 w:0)
	// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn notify_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `6196`
		// Minimum execution time: 170_057 nanoseconds.
		Weight::from_parts(175_315_000, 6196)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::MarkupCoefficient` (r:0 w:1)
	// Proof: `BbBNC::MarkupCoefficient` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_markup_coefficient() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1489`
		// Minimum execution time: 13_627 nanoseconds.
		Weight::from_parts(14_461_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `BbBNC::MarkupCoefficient` (r:1 w:1)
	// Proof: `BbBNC::MarkupCoefficient` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::TotalLock` (r:1 w:1)
	// Proof: `BbBNC::TotalLock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:1)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::LockedTokens` (r:1 w:1)
	// Proof: `BbBNC::LockedTokens` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:0)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:53)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:52 w:0)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:0)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Supply` (r:1 w:0)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:0 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_markup() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2327`
		//  Estimated: `132017`
		// Minimum execution time: 751_111 nanoseconds.
		Weight::from_parts(764_816_000, 132017)
			.saturating_add(T::DbWeight::get().reads(73))
			.saturating_add(T::DbWeight::get().writes(66))
	}
	// Storage: `BbBNC::MarkupCoefficient` (r:1 w:1)
	// Proof: `BbBNC::MarkupCoefficient` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:1)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::LockedTokens` (r:1 w:1)
	// Proof: `BbBNC::LockedTokens` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::TotalLock` (r:1 w:1)
	// Proof: `BbBNC::TotalLock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:0)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:53)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:52 w:0)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:1)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Supply` (r:1 w:0)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn withdraw_markup() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2800`
		//  Estimated: `132490`
		// Minimum execution time: 753_243 nanoseconds.
		Weight::from_parts(767_085_000, 132490)
			.saturating_add(T::DbWeight::get().reads(73))
			.saturating_add(T::DbWeight::get().writes(67))
	}
	// Storage: `BbBNC::UserPositions` (r:1 w:1)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:1)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::Supply` (r:1 w:1)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserLocked` (r:1 w:1)
	// Proof: `BbBNC::UserLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Locks` (r:1 w:1)
	// Proof: `Tokens::Locks` (`max_values`: None, `max_size`: Some(1271), added: 3746, mode: `MaxEncodedLen`)
	// Storage: `Tokens::Accounts` (r:2 w:2)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:2 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:1)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:1)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:1 w:1)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:0 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:0 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn redeem_unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2788`
		//  Estimated: `6253`
		// Minimum execution time: 341_160 nanoseconds.
		Weight::from_parts(353_669_000, 6253)
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(19))
	}
	// Storage: `BbBNC::MarkupCoefficient` (r:1 w:0)
	// Proof: `BbBNC::MarkupCoefficient` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Number` (r:1 w:0)
	// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::LockedTokens` (r:2 w:1)
	// Proof: `BbBNC::LockedTokens` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserMarkupInfos` (r:1 w:1)
	// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::TotalLock` (r:1 w:0)
	// Proof: `BbBNC::TotalLock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	// Storage: `BbBNC::UserPositions` (r:1 w:0)
	// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Locked` (r:1 w:0)
	// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Epoch` (r:1 w:1)
	// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::PointHistory` (r:1 w:1)
	// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Rewards` (r:1 w:1)
	// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::SlopeChanges` (r:1 w:1)
	// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `BbBNC::Supply` (r:1 w:0)
	// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `System::ExecutionPhase` (r:1 w:0)
	// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	// Storage: `System::EventCount` (r:1 w:1)
	// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	// Storage: `System::Events` (r:1 w:1)
	// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn refresh() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1839`
		//  Estimated: `7779`
		// Minimum execution time: 270_276 nanoseconds.
		Weight::from_parts(280_411_000, 7779)
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `BbBNC::UserPositions` (r:1 w:0)
	/// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Locked` (r:1 w:1)
	/// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::ExpiringPositions` (r:2 w:2)
	/// Proof: `BbBNC::ExpiringPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::NextExpiringBlock` (r:1 w:1)
	/// Proof: `BbBNC::NextExpiringBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Supply` (r:1 w:1)
	/// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:1 w:0)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// Storage: `BbBNC::UserMarkupInfos` (r:1 w:0)
	/// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	/// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Epoch` (r:1 w:1)
	/// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::PointHistory` (r:1 w:1)
	/// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserPointEpoch` (r:1 w:1)
	/// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserPointHistory` (r:1 w:1)
	/// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Rewards` (r:1 w:1)
	/// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserRewardPerTokenPaid` (r:1 w:1)
	/// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::SlopeChanges` (r:2 w:2)
	/// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Farming::UserFarmingPool` (r:1 w:1)
	/// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::PermanentLock` (r:0 w:1)
	/// Proof: `BbBNC::PermanentLock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_permanent_lock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1654`
		//  Estimated: `7594`
		// Minimum execution time: 108_949_000 picoseconds.
		Weight::from_parts(112_426_000, 0)
			.saturating_add(Weight::from_parts(0, 7594))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `BbBNC::PermanentLock` (r:10 w:0)
	/// Proof: `BbBNC::PermanentLock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::PositionOwner` (r:10 w:0)
	/// Proof: `BbBNC::PositionOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Locked` (r:10 w:10)
	/// Proof: `BbBNC::Locked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::ExpiringPositions` (r:2 w:2)
	/// Proof: `BbBNC::ExpiringPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::NextExpiringBlock` (r:1 w:1)
	/// Proof: `BbBNC::NextExpiringBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Supply` (r:1 w:1)
	/// Proof: `BbBNC::Supply` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:10 w:0)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// Storage: `BbBNC::UserMarkupInfos` (r:10 w:0)
	/// Proof: `BbBNC::UserMarkupInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::IncentiveConfigs` (r:1 w:1)
	/// Proof: `BbBNC::IncentiveConfigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Epoch` (r:1 w:1)
	/// Proof: `BbBNC::Epoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::PointHistory` (r:1 w:11)
	/// Proof: `BbBNC::PointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::SlopeChanges` (r:4 w:2)
	/// Proof: `BbBNC::SlopeChanges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserPositions` (r:10 w:0)
	/// Proof: `BbBNC::UserPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserPointEpoch` (r:10 w:10)
	/// Proof: `BbBNC::UserPointEpoch` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserPointHistory` (r:10 w:10)
	/// Proof: `BbBNC::UserPointHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::Rewards` (r:10 w:10)
	/// Proof: `BbBNC::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BbBNC::UserRewardPerTokenPaid` (r:10 w:10)
	/// Proof: `BbBNC::UserRewardPerTokenPaid` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Farming::UserFarmingPool` (r:10 w:10)
	/// Proof: `Farming::UserFarmingPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 10]`.
	fn refresh_permanent_locks(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1271 + n * (861 ±0)`
		//  Estimated: `12152 + n * (3335 ±0)`
		// Minimum execution time: 126_793_000 picoseconds.
		Weight::from_parts(41_393_104, 0)
			.saturating_add(Weight::from_parts(0, 12152))
			// Standard Error: 189_730
			.saturating_add(Weight::from_parts(91_047_177, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().reads((11_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3335).saturating_mul(n.into()))
	}
}
