// This file is part of Bifrost.

// Copyright (C) Liebi Technologies PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for bifrost_system_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-03-26, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `bifrost-jenkins`, CPU: `Intel(R) Xeon(R) CPU E5-26xx v4`
//! WASM-EXECUTION: Compiled, CHAIN: Some("bifrost-kusama-local"), DB CACHE: 1024

// Executed Command:
// target/release/bifrost
// benchmark
// pallet
// --chain=bifrost-kusama-local
// --steps=50
// --repeat=20
// --pallet=bifrost_system_staking
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/bifrost-kusama/src/weights/bifrost_system_staking.rs
// --template=./weight-template/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions for bifrost_system_staking.
pub struct BifrostWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> bifrost_system_staking::WeightInfo for BifrostWeight<T> {
	// Storage: `SystemStaking::TokenList` (r:1 w:0)
	// Proof: `SystemStaking::TokenList` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `SystemStaking::Round` (r:1 w:0)
	// Proof: `SystemStaking::Round` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `SystemStaking::TokenStatus` (r:2 w:0)
	// Proof: `SystemStaking::TokenStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `6385`
		// Minimum execution time: 30_942 nanoseconds.
		Weight::from_parts(31_597_000, 6385)
			.saturating_add(T::DbWeight::get().reads(4))
	}
	// Storage: `SystemStaking::TokenStatus` (r:1 w:1)
	// Proof: `SystemStaking::TokenStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `SystemStaking::TokenList` (r:1 w:1)
	// Proof: `SystemStaking::TokenList` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn token_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3574`
		// Minimum execution time: 35_136 nanoseconds.
		Weight::from_parts(35_890_000, 3574)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: `SystemStaking::TokenStatus` (r:1 w:1)
	// Proof: `SystemStaking::TokenStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Farming::PoolInfos` (r:1 w:0)
	// Proof: `Farming::PoolInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn refresh_token_info() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `3835`
		// Minimum execution time: 47_920 nanoseconds.
		Weight::from_parts(48_714_000, 3835)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `SystemStaking::TokenStatus` (r:1 w:0)
	// Proof: `SystemStaking::TokenStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Accounts` (r:1 w:0)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `VtokenMinting::SupportedEth` (r:1 w:0)
	// Proof: `VtokenMinting::SupportedEth` (`max_values`: Some(1), `max_size`: Some(141), added: 636, mode: `MaxEncodedLen`)
	// Storage: `VtokenMinting::TokenPool` (r:1 w:0)
	// Proof: `VtokenMinting::TokenPool` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	fn payout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `706`
		//  Estimated: `4171`
		// Minimum execution time: 72_608 nanoseconds.
		Weight::from_parts(73_435_000, 4171)
			.saturating_add(T::DbWeight::get().reads(5))
	}
	fn on_redeem_success() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_416 nanoseconds.
		Weight::from_parts(1_618_000, 0)
	}
	fn on_redeemed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_451 nanoseconds.
		Weight::from_parts(1_628_000, 0)
	}
	// Storage: `SystemStaking::TokenList` (r:1 w:1)
	// Proof: `SystemStaking::TokenList` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `SystemStaking::TokenStatus` (r:0 w:1)
	// Proof: `SystemStaking::TokenStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1654`
		// Minimum execution time: 22_659 nanoseconds.
		Weight::from_parts(23_810_000, 1654)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
