// This file is part of Bifrost.

// Copyright (C) Liebi Technologies PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for bifrost_cross_in_out
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-03-26, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `bifrost-jenkins`, CPU: `Intel(R) Xeon(R) CPU E5-26xx v4`
//! WASM-EXECUTION: Compiled, CHAIN: Some("bifrost-kusama-local"), DB CACHE: 1024

// Executed Command:
// target/release/bifrost
// benchmark
// pallet
// --chain=bifrost-kusama-local
// --steps=50
// --repeat=20
// --pallet=bifrost_cross_in_out
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/bifrost-kusama/src/weights/bifrost_cross_in_out.rs
// --template=./weight-template/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions for bifrost_cross_in_out.
pub struct BifrostWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> bifrost_cross_in_out::WeightInfo for BifrostWeight<T> {
	// Storage: `CrossInOut::CrossCurrencyRegistry` (r:1 w:1)
	// Proof: `CrossInOut::CrossCurrencyRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deregister_currency_for_cross_in_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `3584`
		// Minimum execution time: 34_057 nanoseconds.
		Weight::from_parts(34_826_000, 3584)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `CrossInOut::CrossingMinimumAmount` (r:0 w:1)
	// Proof: `CrossInOut::CrossingMinimumAmount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_crossing_minimum_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_469 nanoseconds.
		Weight::from_parts(21_234_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `CrossInOut::RegisterWhiteList` (r:1 w:1)
	// Proof: `CrossInOut::RegisterWhiteList` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_to_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 37_269 nanoseconds.
		Weight::from_parts(38_553_000, 3541)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `CrossInOut::RegisterWhiteList` (r:1 w:1)
	// Proof: `CrossInOut::RegisterWhiteList` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_from_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `3619`
		// Minimum execution time: 35_454 nanoseconds.
		Weight::from_parts(36_222_000, 3619)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `CrossInOut::RegisterWhiteList` (r:1 w:0)
	// Proof: `CrossInOut::RegisterWhiteList` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::CrossCurrencyRegistry` (r:1 w:0)
	// Proof: `CrossInOut::CrossCurrencyRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::AccountToOuterMultilocation` (r:1 w:1)
	// Proof: `CrossInOut::AccountToOuterMultilocation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::OuterMultilocationToAccount` (r:0 w:1)
	// Proof: `CrossInOut::OuterMultilocationToAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `3658`
		// Minimum execution time: 59_302 nanoseconds.
		Weight::from_parts(60_150_000, 3658)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: `CrossInOut::CrossCurrencyRegistry` (r:1 w:0)
	// Proof: `CrossInOut::CrossCurrencyRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::CrossingMinimumAmount` (r:1 w:0)
	// Proof: `CrossInOut::CrossingMinimumAmount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::Accounts` (r:1 w:1)
	// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	// Storage: `CrossInOut::AccountToOuterMultilocation` (r:1 w:0)
	// Proof: `CrossInOut::AccountToOuterMultilocation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `AssetRegistry::CurrencyMetadatas` (r:1 w:0)
	// Proof: `AssetRegistry::CurrencyMetadatas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Tokens::TotalIssuance` (r:1 w:1)
	// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	fn cross_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1011`
		//  Estimated: `4476`
		// Minimum execution time: 120_289 nanoseconds.
		Weight::from_parts(124_470_000, 4476)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: `CrossInOut::CrossCurrencyRegistry` (r:1 w:0)
	// Proof: `CrossInOut::CrossCurrencyRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::AccountToOuterMultilocation` (r:1 w:1)
	// Proof: `CrossInOut::AccountToOuterMultilocation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `CrossInOut::OuterMultilocationToAccount` (r:0 w:1)
	// Proof: `CrossInOut::OuterMultilocationToAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_outer_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `3777`
		// Minimum execution time: 57_811 nanoseconds.
		Weight::from_parts(59_636_000, 3777)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
