[package]
name = "westend-system-emulated-network"
description = "Westend System emulated network"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
emulated-integration-tests-common.workspace = true
westend-emulated-chain.workspace = true
asset-hub-westend-emulated-chain.workspace = true
bridge-hub-westend-emulated-chain.workspace = true
penpal-emulated-chain.workspace = true
bifrost-kusama-emulated-chain = { path = "../../../integration-tests/chains/bifrost-kusama" }
