// This file is part of Bifrost.

// Copyright (C) Liebi Technologies PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

use crate::common::types::XcmFee;
use crate::*;
use frame_support::traits::OnRuntimeUpgrade;
#[cfg(feature = "try-runtime")]
use scale_info::prelude::vec::Vec;
use sp_runtime::Permill;
#[cfg(feature = "try-runtime")]
use sp_runtime::TryRuntimeError;

const LOG_TARGET: &str = "SLP-V2::migration";

pub mod v1_struct {
	use super::*;

	#[derive(Encode, Decode)]
	pub struct ProtocolConfiguration<AccountId> {
		/// Xcm fee for the task
		pub xcm_task_fee: XcmFee,
		/// Protocol fee rate
		pub protocol_fee_rate: Permill,
		/// Unlock period
		pub unlock_period: TimeUnit,
		/// Staking Protocol operator
		pub operator: AccountId,
		/// Max update token exchange rate
		pub max_update_token_exchange_rate: Permill,
		/// Update time unit interval
		pub update_time_unit_interval: BlockNumber,
		/// Update exchange rate interval
		pub update_exchange_rate_interval: BlockNumber,
	}
}

pub struct SlpV2Migration<T>(sp_std::marker::PhantomData<T>);
impl<T: Config> OnRuntimeUpgrade for SlpV2Migration<T> {
	fn on_runtime_upgrade() -> frame_support::weights::Weight {
		// Check the storage version
		let in_code_version = Pallet::<T>::in_code_storage_version();
		let on_chain_version = Pallet::<T>::on_chain_storage_version();
		if on_chain_version < in_code_version {
			// Transform storage values
			// We transform the storage values from the old into the new format.
			log::info!(target: LOG_TARGET, "Start to migrate ConfigurationByStakingProtocol storage...");
			let mut reads = 0u64;
			let mut writes = 0u64;

			ConfigurationByStakingProtocol::<T>::translate::<
				v1_struct::ProtocolConfiguration<T::AccountId>,
				_,
			>(|_staking_protocol, old| {
				reads += 1;
				writes += 1;

				Some(ProtocolConfiguration {
					xcm_task_fee: old.xcm_task_fee,
					protocol_fee_rate: old.protocol_fee_rate,
					unlock_period: old.unlock_period,
					operator: old.operator,
					max_update_token_exchange_rate: old.max_update_token_exchange_rate,
					update_time_unit_interval: old.update_time_unit_interval,
					update_exchange_rate_interval: old.update_exchange_rate_interval,
					// remote_fee_location defaults to None
					remote_fee_location: None,
				})
			});

			StorageVersion::new(1).put::<Pallet<T>>();
			T::DbWeight::get().reads_writes(reads, writes)
		} else {
			// We don't do anything here.
			Weight::zero()
		}
	}

	#[cfg(feature = "try-runtime")]
	fn pre_upgrade() -> Result<Vec<u8>, TryRuntimeError> {
		let cnt = ConfigurationByStakingProtocol::<T>::iter().count();
		// print out the pre-migrate storage count
		log::info!(target: LOG_TARGET, "ConfigurationByStakingProtocol pre-migrate storage count: {cnt:?}");

		Ok((cnt as u32).encode())
	}

	#[cfg(feature = "try-runtime")]
	fn post_upgrade(cnt: Vec<u8>) -> Result<(), TryRuntimeError> {
		let cnt: u32 = Decode::decode(&mut cnt.as_slice())
			.expect("the state parameter should be something that was generated by pre_upgrade");

		let cnt_new = ConfigurationByStakingProtocol::<T>::iter().count();
		// print out the post-migrate storage count
		log::info!(
			target: LOG_TARGET,
			"ConfigurationByStakingProtocol post-migrate storage count: {cnt_new:?}"
		);
		ensure!(
			cnt == cnt_new as u32,
			"ConfigurationByStakingProtocol post-migrate storage count not match"
		);

		Ok(())
	}
}
