[package]
name = "polkadot-kusama-system-emulated-network"
description = "Rococo<>Westend emulated bridged network"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
emulated-integration-tests-common.workspace = true
polkadot-emulated-chain.workspace = true
kusama-emulated-chain.workspace = true
kusama-emulated-chain.default-features = true
asset-hub-polkadot-emulated-chain.workspace = true
asset-hub-kusama-emulated-chain.workspace = true
bridge-hub-polkadot-emulated-chain.workspace = true
bridge-hub-kusama-emulated-chain.workspace = true
bifrost-polkadot-emulated-chain = { path = "../../../../integration-tests/emulated/chains/bifrost-polkadot" }
bifrost-kusama-emulated-chain = { path = "../../../../integration-tests/emulated/chains/bifrost-kusama" }
