[package]
name = "bifrost-polkadot-emulated-chain"
description = "Bifrost Polkadot emulated chain"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
sp-core.workspace = true
sp-keyring.workspace = true
frame-support.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
bifrost-polkadot-runtime.workspace = true
bifrost-polkadot-runtime.default-features = true
bifrost-primitives.workspace = true
bifrost-primitives.default-features = true
rococo-emulated-chain.workspace = true
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }
xcm.workspace = true
bp-bridge-hub-rococo.workspace = true
