#!/bin/bash

# import common functions
source "$FRAMEWORK_PATH/utils/bridges.sh"

# Expected sovereign accounts.
#
# Generated by:
#
##[test]
#fn generate_sovereign_accounts() {
#	use polkadot_parachain_primitives::primitives::Sibling;
#	use sp_core::crypto::Ss58Codec;
#
#	parameter_types! {
#		pub UniversalLocationAHP: InteriorLocation = [GlobalConsensus(Polkadot), Parachain(1000)].into();
#		pub UniversalLocationAHK: InteriorLocation = [GlobalConsensus(Kusama), Parachain(1000)].into();
#	}
#
#
#	println!(
#		"GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			GlobalConsensusConvertsFor::<UniversalLocationAHK, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Polkadot)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(1000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#
#	println!(
#		"GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			GlobalConsensusConvertsFor::<UniversalLocationAHP, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Kusama)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#	println!(
#		"ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(1000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#}
GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT="FxqimVubBRPqJ8kTwb3wL7G4q645hEkBEnXPyttLsTrFc5Q"
ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA="FBeL7EFTDeHnuViqaUHUXvhhUusN5FawDmHgfvzF97DXFr3"
GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT="14zcUAhP5XypiFQWA3b1AnGKrhZqR4XWUo4deWkwuN5y983G"
ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT="13cKp89SgdtqUngo2WiEijPrQWdHFhzYZLf2TJePKRvExk7o"
BIFROST_KUSAMA_SIBLING_ACCOUNT="FBeL7EAr6uyrdTJqc93nzMuZUA5jn7jyBYSj214FMnEQru8"
BIFROST_POLKADOT_SIBLING_ACCOUNT="13cKp89TtYknbyYnqnF6dWN75q5ZosvFSuqzoEVkUAaNR47A"
BOB_SOVEREIGN_ACCOUNT_AT_KUSAMA="FoQJpPyadYccjavVdTWxpxU7rUEaYhfLCPwXgkfD6Zat9QP"
BOB_SOVEREIGN_ACCOUNT_AT_POLKADOT="14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3"

# Expected sovereign accounts for rewards on BridgeHubs.
#
# Generated by:
##[test]
#fn generate_sovereign_accounts_for_rewards() {
#	use bp_messages::LaneId;
#	use bp_relayers::{PayRewardFromAccount, RewardsAccountOwner, RewardsAccountParams};
#	use sp_core::crypto::Ss58Codec;
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#}
ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain="13E5fui93Uyua5RtDv2LQj4aVBBHo6YREe3n6CBwYdqNqoxj"
ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain="13E5fui93Uyua5RtDv2c9kcAbfrVFeeHyJzHe8sn1Ti77Afd"
ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain="EoQBtnwp4jMtCEpV7C88rKrz6x1qMBh2z74ibGSqtZRnuMM"
ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain="EoQBtnwp4jMtCEpV7CPsssT6bdDHuHZmf3aGXxHJiSA4Dz3"

LANE_ID="00000001"
XCM_VERSION=5

AHK_DOT_ED=10000000
DOT=10000000000

AHP_KSM_ED=10000000
KSM=1000000000000

TEER_ED=1000000000
BNC=1000000000000

function init_polkadot_kusama() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge polkadot-to-bridge-hub-kusama \
	--source-uri ws://localhost:9942 \
	--source-version-mode Auto \
	--target-uri ws://localhost:8945 \
	--target-version-mode Auto \
	--target-signer //Alice
}

function init_kusama_polkadot() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge kusama-to-bridge-hub-polkadot \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Alice
}

function run_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers-and-messages bridge-hub-kusama-bridge-hub-polkadot \
        --polkadot-uri ws://localhost:9942 \
        --polkadot-version-mode Auto \
        --bridge-hub-polkadot-uri ws://localhost:8943 \
        --bridge-hub-polkadot-version-mode Auto \
        --bridge-hub-polkadot-signer //Charlie \
        --bridge-hub-polkadot-transactions-mortality 4 \
        --kusama-uri ws://localhost:9945 \
        --kusama-version-mode Auto \
        --bridge-hub-kusama-uri ws://localhost:8945 \
        --bridge-hub-kusama-version-mode Auto \
        --bridge-hub-kusama-signer //Charlie \
        --bridge-hub-kusama-transactions-mortality 4 \
        --lane "${LANE_ID}"
}

function run_finality_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers polkadot-to-bridge-hub-kusama \
        --only-free-headers \
        --source-uri ws://localhost:9942 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Charlie \
        --target-transactions-mortality 4&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers kusama-to-bridge-hub-polkadot \
        --only-free-headers \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Charlie \
        --target-transactions-mortality 4
}

function run_parachains_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-parachains bridge-hub-polkadot-to-bridge-hub-kusama \
        --only-free-headers \
        --source-uri ws://localhost:9942 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Dave \
        --target-transactions-mortality 4&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-parachains bridge-hub-kusama-to-bridge-hub-polkadot \
        --only-free-headers \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Dave \
        --target-transactions-mortality 4
}

function run_messages_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-messages bridge-hub-polkadot-to-bridge-hub-kusama \
        --source-uri ws://localhost:8943 \
        --source-version-mode Auto \
        --source-signer //Eve \
        --source-transactions-mortality 4 \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Eve \
        --target-transactions-mortality 4 \
        --lane $LANE_ID&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-messages bridge-hub-kusama-to-bridge-hub-polkadot \
        --source-uri ws://localhost:8945 \
        --source-version-mode Auto \
        --source-signer //Ferdie \
        --source-transactions-mortality 4 \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Ferdie \
        --target-transactions-mortality 4 \
        --lane $LANE_ID
}

case "$1" in
  run-relay)
      init_kusama_polkadot
      init_polkadot_kusama
      run_relay
      ;;
  run-finality-relay)
      init_kusama_polkadot
      init_polkadot_kusama
      run_finality_relay
      ;;
  run-parachains-relay)
      run_parachains_relay
      ;;
  run-messages-relay)
      run_messages_relay
      ;;
  init-polkadot-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 1002 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 1000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 2030 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          2030 1000 4 524288
      # governance set XCM version of remote AssetHubKusama on AHP
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      # governance set XCM version of remote BridgeHubKusama on BHP
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-asset-hub-polkadot-local)
      ensure_polkadot_js_api
      # create pool for DOT and wKSM
      create_pool \
          "ws://127.0.0.1:9910" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Kusama" }] } }')"
      # Create liquidity in the pool @ 10 DOT = 4 KSM (100 DOT = 40KSM)
      add_liquidity \
          "ws://127.0.0.1:9910" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Kusama"}] } }')" \
          1000000000000 \
          40000000000000 \
          "$BOB_SOVEREIGN_ACCOUNT_AT_POLKADOT"
      # create foreign assets for native Kusama token (governance call on Polkadot)
      force_create_foreign_asset \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2030 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
          "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" \
          $TEER_ED \
          false
     call_polkadot_js_api \
         --ws "ws://127.0.0.1:9910" \
         --seed "//Alice" \
         tx.foreignAssets.mint \
             "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2030 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
             "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" \
             9000000000000000
     # create pool for DOT and BNC
      create_pool \
          "ws://127.0.0.1:9910" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2030 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')"
      sleep 10
     # Create liquidity in the pool @ 10 DOT = 400 BNC
      call_polkadot_js_api \
        --ws "ws://127.0.0.1:9910" \
        --seed "//Alice" \
        tx.assetConversion.addLiquidity \
             "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
             "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2030 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
            "100000000000" \
            "400000000000000" \
            "1" \
            "1" \
            "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5"

      # SA of sibling bifrost pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$BIFROST_POLKADOT_SIBLING_ACCOUNT" \
          $((25 * $DOT))

      # SA of sibling bifrost pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "16QW3BbuXU4YmBJdGzKmqyU3XJTKrf6suM9kosgHbLp8jx4c" \
          $((100 * $DOT))
      # set XCM version of remote AssetHubKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-polkadot-local)
      ensure_polkadot_js_api
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT" \
          $((25 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain" \
          $((25 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain" \
          $((25 * $DOT))
      # set XCM version of remote BridgeHubKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-kusama-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 1002 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 1000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 2001 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          2001 1000 4 524288

      # governance set XCM version of remote AssetHubPolkadot on AHK
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      # governance set XCM version of remote BridgeHubPolkadot on BHK
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-asset-hub-kusama-local)
      ensure_polkadot_js_api
      # create pool for KSM and wDOT
      create_pool \
          "ws://127.0.0.1:9010" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Polkadot" }] } }')"
      # Create liquidity in the pool @ 1 KSM = 2.5 DOT (50 KSM = 125 DOT).
      add_liquidity \
          "ws://127.0.0.1:9010" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Polkadot"}] } }')" \
          25000000000000 \
          1250000000000 \
          "$BOB_SOVEREIGN_ACCOUNT_AT_KUSAMA"
      force_create_foreign_asset \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2001 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
          "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" \
          $TEER_ED \
          false
     call_polkadot_js_api \
         --ws "ws://127.0.0.1:9010" \
         --seed "//Alice" \
         tx.foreignAssets.mint \
             "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2001 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
             "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" \
             9000000000000000
     # create pool for KSM and BNC
      create_pool \
          "ws://127.0.0.1:9010" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2001 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')"
      sleep 10
       # Create liquidity in the pool @ 10 KSM = 400 BNC
      call_polkadot_js_api \
        --ws "ws://127.0.0.1:9010" \
        --seed "//Alice" \
        tx.assetConversion.addLiquidity \
            "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
            "$(jq --null-input '{ "parents": 1, "interior": { "X2": [ { "Parachain": 2001 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')" \
            "10000000000000" \
            "400000000000000" \
            "1" \
            "1" \
            "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5"

      # SA of sibling bifrost pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$BIFROST_KUSAMA_SIBLING_ACCOUNT" \
          $((25 * $KSM))
      # SA of sibling bifrost pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "13iKE412s9zhWSHmR9A7V39P42Wzj3toE123Td9mLjzbwrpe" \
          $((100 * $KSM))
      # set XCM version of remote AssetHubPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-kusama-local)
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA" \
          $((25 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain" \
          $((25 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain" \
          $((25 * $KSM))
      # set XCM version of remote BridgeHubPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bifrost-kusama-local)
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9144" \
          "//Alice" \
          "$ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA" \
          $((25 * $TEER))
      # root origin local account
      transfer_balance \
          "ws://127.0.0.1:9144" \
          "//Alice" \
          "2JZNyFtn2KWCcgU6vM7Mh7TXR2BGCdewgPxZCQaofwcbF5cn" \
          $((100 * $TEER))
      # sovereign account of BK on PAH
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "14DXRZEfzojXowgGnamfGzTjnMERF9cVWRkdHHYQFiTsDiXB" \
          $((500 * $DOT))

      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.forceSetLocation \
              "$(jq --null-input '{ "Native": "BNC" }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } } }')" \
              "$(jq --null-input '{ "refTime": 0, "proofSize": 0 }')"

      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.forceSetLocation \
              "$(jq --null-input '{ "Token": "KSM" }')" \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": "Here" } }')" \
              "$(jq --null-input '{ "refTime": 0, "proofSize": 0 }')"
      # set XCM version of remote IntegriteePolkadot for relay and AH
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          2001 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 2030 } ] } }')" \
          $XCM_VERSION
      # send 9000 BNC to KAH Alice for pool
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          tx.polkadotXcm.transferAssets \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } } }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
              "$(jq --null-input '{ "V4": [ { "id": { "parents": 0, "interior": { "X1": [{ "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } }] } }, "fun": { "Fungible": '9000000000000000' } }, { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '100000000000' } } ] }')" \
              "1" \
              "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on KAH"
      sleep 30
      # provide liquidity to BNC/KSM pool on KAH @ 50TEER = 1KSM (5000 BNC = 100KSM)
      add_liquidity \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "Parachain": 2001 }, { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } }')"
          1000000000000 \
          800000000000000 \
          "//Alice"
      ;;
  init-bifrost-polkadot-local)
      # SA of sibling asset hub pays for the inwards execution
      transfer_balance \
          "ws://127.0.0.1:9244" \
          "//Alice" \
          "$ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT" \
          $((25 * $TEER))
      # root origin local account on BP
      transfer_balance \
          "ws://127.0.0.1:9244" \
          "//Alice" \
          "2JZNyFtn2KWCcgU6vM7Mh7TXR2BGCdewgPxZCQaofwcbF5cn" \
          $((100 * $TEER))
      # sovereign account of BP on KAH
      transfer_balance \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "J4jPjaphmo2vzeEWEKaXfB1u3W2VWxDTNwyFuSMvStoQb4F" \
          $((10 * $KSM))
      # set XCM version of remote IntegriteeKusama for relay and AH
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          2030 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 2001 } ] } }')" \
          $XCM_VERSION
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.forceSetLocation \
              "$(jq --null-input '{ "Native": "BNC" }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "GeneralKey": { "length": 2, "data": [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] } } ] } } }')" \
              "$(jq --null-input '{ "refTime": 0, "proofSize": 0 }')"

      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.forceSetLocation \
              "$(jq --null-input '{ "Token2": 0 }')" \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": "Here" } }')" \
              "$(jq --null-input '{ "refTime": 0, "proofSize": 0 }')"

      # above call has no authority over bifrost. need to do it locally
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 2001 } ] } }')" \
              $XCM_VERSION
      # also for PAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } }')" \
              $XCM_VERSION
      # create a BNC/DOT pool on PAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9910" \
          --seed "//Alice" \
          tx.assetConversion.createPool \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2030 }]}}')" \
      # send 9000 BNC to PAH Alice for pool
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          tx.polkadotXcm.transferAssets \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } } }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
              "$(jq --null-input '{ "V4": [ { "id": { "parents": 0, "interior": "Here" }, "fun": { "Fungible": '9000000000000000' } }, { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '100000000000' } } ] }')" \
              "1" \
              "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on PAH"
      sleep 30
      # provide liquidity to BNC/DOT pool on PAH @ 20TEER = 1 DOT (5000 BNC = 250 DOT)
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9910" \
          --seed "//Alice" \
          tx.assetConversion.addLiquidity \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2030 }]}}')" \
              "2500000000000" \
              "5000000000000000" \
              "1" \
              "1" \
              "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5"
      # set XCM fee params: BNC / DOT / KSM. may be way too high
#      call_polkadot_js_api \
#          --ws "ws://127.0.0.1:9244" \
#          --seed "//Alice" \
#          --sudo \
#          tx.porteer.setXcmFeeParams \
#              "$(jq --null-input '{ "local_equivalent_sum": 42, "hop1": 10000000000000, "hop2": 10000000000, "hop3": 200000000000 }')"
      ;;
  reserve-transfer-assets-from-asset-hub-polkadot-local)
      amount=$2
      ensure_polkadot_js_api
      # send DOTs to Alice account on AHK
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  withdraw-reserve-assets-from-asset-hub-polkadot-local)
      amount=$2
      ensure_polkadot_js_api
      # send back some wrappedKSMs to Alice account on AHK
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 2, "interior": { "X1": [ { "GlobalConsensus": "Kusama" } ] } }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  reserve-transfer-assets-from-asset-hub-kusama-local)
      amount=$2
      ensure_polkadot_js_api
      # send KSMs to Alice account on AHP
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  withdraw-reserve-assets-from-asset-hub-kusama-local)
      amount=$2
      ensure_polkadot_js_api
      # send back some wrappedDOTs to Alice account on AHP
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 2, "interior": { "X1": [ { "GlobalConsensus": "Polkadot" } ] } }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  *)
      echo "A command is require. Supported commands for:
      Local (zombienet) run:
            - run-relay
            - run-finality-relay
            - run-parachains-relay
            - run-messages-relay
            - init-asset-hub-polkadot-local
            - init-bridge-hub-polkadot-local
            - init-asset-hub-kusama-local
            - init-bridge-hub-kusama-local
            - reserve-transfer-assets-from-asset-hub-polkadot-local
            - withdraw-reserve-assets-from-asset-hub-polkadot-local
            - reserve-transfer-assets-from-asset-hub-kusama-local
            - withdraw-reserve-assets-from-asset-hub-kusama-local";
      exit 1
      ;;
esac