[package]
name = "penpal-emulated-chain"
description = "Penpal emulated chain"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
sp-core.workspace = true
sp-keyring.workspace = true
frame-support.workspace = true
xcm.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
penpal-runtime.workspace = true
penpal-runtime.default-features = true
