name: Release

env:
  SUBWASM_VERSION: 0.20.0

on:
  push:
    tags:
      - 'bifrost-*'
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master 
        with:
          components: rustfmt
          target: wasm32-unknown-unknown
          toolchain: nightly-2023-05-22

     
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          # body_path: CHANGELOG.txt
          append_body: true
          prerelease: true

